server:
  port: 8445
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: mypass
    key-store-type: PKCS12

REDIRECT_URI: https://localhost:8445/index.html
APP_ID: 695569147572856
APP_SECRET: 77ce596cdd2fb35346c68594a3775056

spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      database: users
      uri: mongodb+srv://admin:admin@weather-abfut.mongodb.net/test?retryWrites=true&w=majority
      admin: admin
      password: admin
