server:
  port: 8081

security:
  oauth2:
    client:
      clientId: 695569147572856
      clientSecret: 77ce596cdd2fb35346c68594a3775056
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      scope: public_profile, user_birthday
    resource:
      userInfoUri: https://graph.facebook.com/me

spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      database: users
      uri: mongodb+srv://admin:admin@weather-abfut.mongodb.net/test?retryWrites=true&w=majority
      admin: admin
      password: admin
